### PR TITLE
added id tags from JS to the input page html

### PR DESCRIPTION
**Pull request by ashclandry**
I added some of the ids from the JS file to the input page. @macgreene14  can you let me know what is missing?

### CODE REVIEW

**Review by bp4924 — APPROVED** [review]
I think those are the only things he looks for in the index.html. He also looks for cocktailContent, but I don't see that anywhere else.

**Comment by ashclandry** [comment]
Good catch Bernie! I just added that to the HTML, and it seems to be working in the console.log

**Comment by macgreene14** [comment]
Looks good

**Review by macgreene14 — APPROVED** [review]
Looks good

**Pull request merged**
