### PR TITLE
Landing and modal

### PR DESCRIPTION
**Pull request by isayani**
Landing and modal finished (without JavaScript)
files updated: index.html and style.css

### CODE REVIEW

**Review by ashclandry — DISMISSED** [review]
Looks great Insha!

**Review by macgreene14 — DISMISSED** [review]
👍

**Comment by macgreene14** [comment]
I attempted to approve, but there is a conflict that needs to be resolved prior to merging. Let's review this as a team during the next working session.

**Review by ashclandry — DISMISSED** [review]
Looks good!

**Review by macgreene14 — APPROVED** [review]
I like it

**Review by ashclandry — APPROVED** [review]
I like it i love it

**Pull request merged**
